services:
  api-gateway:
    build:
      context: ./src/BookLinkServer/api-gateway
    ports:
      - "4001:4001" 
    depends_on:
      - user-service
    networks:
      - booknet

  book-search:
    build:
      context: ./src/BookLinkServer/book-search
    ports:
      - "4000:4000" 
    networks:
      - booknet

  user-service:
    build:
      context: ./src/BookLinkServer/user-service
    ports:
      - "5000:5000"
    env_file:
      - ./src/BookLinkServer/user-service/.env   
    networks:
      - booknet 

  frontend:
    build:
      context: ./src/BookLinkCliente
    ports:
      - "3000:80"  
    depends_on:
      - api-gateway
    networks:
      - booknet

networks:
  booknet:
    driver: bridge
